config/routes.rb
Rails.application.routes.draw do
 # 管理者側deviseルーティング
  devise_for :admin, skip: :all
   devise_scope :admin do
     get "/admin/sign_in", to: "admin/sessions#new", as: :new_admin_session
     post "/admin/sign_in", to: "admin/sessions#create", as: :admin_session
     delete "/admin/sign_out", to: "admin/sessions#destroy", as: :destroy_admin_session
   end
# メンバー側deviseルーティング
  devise_for :members, skip: :all
   devise_scope :member do
     get "/members/sign_up", to: "public/registrations#new", as: :new_member_registration
     post "/members", to: "public/registrations#create", as: :member_registration
     get "/members/sign_in", to: "public/sessions#new", as: :new_member_session
     post "/members/sign_in", to: "public/sessions#create", as: :member_session
     delete "/members/sign_out", to: "public/sessions#destroy", as: :destroy_member_session
     post '/members/guest_sign_in', to: 'public/sessions#guest_sign_in'
   end
# メンバー側ルーティング
  scope module: :public do
    root :to => "homes#top"
    get "/about" => "homes#about"
    resources :members,only:[:show,:edit,:update] do
     resource :playing_games,only:[:create,:destroy]
     get "/playing_games/index", to: "playing_games#index", as: :playing_games_index
     resource :relationships,only:[:create,:destroy]
     get "/relationships/followings",to: "relationships#followings", as: :followings_index
     get "/relationships/followers",to: "relationships#followers", as: :followers_index
    end
    resources :posts,only:[:index,:show,:create,:destroy,:new] do
     patch "/close", to: "posts#close", as: :close
     resources :comments,only:[:create,:destroy]
     resource :favorites,only:[:create,:destroy]
    end
    resources :games,only:[:index,:show]
    get "/search", to: "games#search",as: :search
    resources :chats,only:[:show,:create]
    resources :contacts,only:[:new,:create]
    post "/contacts/confirm",to: "contacts#confirm", as: :confirm
    post "/contacts/back",to: "contacts#back", as: :back
    get "/done",to: "contacts#done", as: :done
    resources :notifications,only:[:index], as: :notifications
    resources :announcements,only:[:index,:show]
  end
# 管理者側ルーティング
  namespace :admin do
   resources :games
   resources :announcements,only:[:new,:create,:edit,:update,:destroy]
   resources :members,only:[:index] do
     patch "/close", to: "members#close"
   end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction,    length: { maximum: 60 }
  validates :name, presence: true, length: { maximum: 10}

  attachment :image


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :playing_games, dependent: :destroy
  has_many :games, through: :playing_games

  has_many :following, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :following, source: :follower
  has_many :follower_user, through: :follower, source: :following

  has_many :entries
  has_many :chats
  has_many :rooms, through: :entries

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def follow(user_id)
    following.create(follower_id: user_id)
  end

  def unfollow(user_id)
    following.find_by(follower_id: user_id).destroy
  end

  def following?(user_id)
    following_user.include?(user_id)
  end

  # フォロー通知
  def create_notification_follow!(current_member)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_member.id, id, 'follow'])
    if temp.blank?
      notification = current_member.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  # 部分一致で検索
  def self.search(search)
    if search
      where("name LIKE ?","%#{search}%")
    else
      all
    end
  end
  # 論理削除済みは弾く
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "ゲストユーザー"
    end
  end


end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

  before_action :authenticate_admin!

  def index
    if params[:search]
      @members = Member.search(params[:search])
    else
      @members = Member.all
    end
  end

# 管理者がメンバーのログイン権限を剥奪
  def close
    member = Member.find(params[:member_id])
    if member.is_deleted?
      member.update(is_deleted: false)
      redirect_back(fallback_location: root_path)
    else
      member.update(is_deleted: true)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center my-5">
    <h3 class="mr-5">メンバー一覧</h3>
    <%= form_with url: admin_members_path,method: :get, local: true do |f| %>
      <%= f.text_field :search, value: params[:search] %>
      <%= f.submit "検索", name: nil %>
    <% end %>
  </div>

  <div class="row">
    <table class="table w-50 text-left mx-auto border">
      <thead class="thead-light d-block" style="width:568px;">
        <tr class="thead-light">
          <th style="width:100px;"></th>
          <th style="width:268px;">メンバー名</th>
          <th style="width:200px;"></th>
        </tr>
      </thead>
      <tbody class="overflow-auto d-block" style="height:400px; width:568px;">
        <% @members.each do |member|%>
        <tr>
          <td class="pt-3" style="width:100px;">
            <%= link_to member_path(member),class:"text-decoration-none" do %>
               <%= attachment_image_tag member, :image, format: "jpg", fallback: "member_img.jpg",size: "30x30"%>
            <% end %>
          </td>
          <td style="width:268px;"><%= link_to member.name,member_path(member),class:"text-dark text-decoration-none"%></td>
          <td class="text-right" style="width:200px;">
            <% if admin_signed_in? %>
              <%if member.is_deleted? %>
                <%= link_to "凍結を解除", admin_member_close_path(member), method: :patch, class:"btn btn-primary",data: {confirm:"メンバーの凍結を解除しますか？",cancel:"やめる",commit:"解除する"},title:"確認"%>
              <% else%>
                <%= link_to "凍結させる", admin_member_close_path(member), method: :patch, class:"btn btn-danger",data: {confirm:"メンバーを凍結させますか？",cancel:"やめる",commit:"凍結させる"},title:"確認"%>
              <% end %>
            <%end%>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>