config/routes.rb
Rails.application.routes.draw do
 # 管理者側deviseルーティング
  devise_for :admin, skip: :all
   devise_scope :admin do
     get "/admin/sign_in", to: "admin/sessions#new", as: :new_admin_session
     post "/admin/sign_in", to: "admin/sessions#create", as: :admin_session
     delete "/admin/sign_out", to: "admin/sessions#destroy", as: :destroy_admin_session
   end
# メンバー側deviseルーティング
  devise_for :members, skip: :all
   devise_scope :member do
     get "/members/sign_up", to: "public/registrations#new", as: :new_member_registration
     post "/members", to: "public/registrations#create", as: :member_registration
     get "/members/sign_in", to: "public/sessions#new", as: :new_member_session
     post "/members/sign_in", to: "public/sessions#create", as: :member_session
     delete "/members/sign_out", to: "public/sessions#destroy", as: :destroy_member_session
     post '/members/guest_sign_in', to: 'public/sessions#guest_sign_in'
   end
# メンバー側ルーティング
  scope module: :public do
    root :to => "homes#top"
    get "/about" => "homes#about"
    resources :members,only:[:show,:edit,:update] do
     resource :playing_games,only:[:create,:destroy]
     get "/playing_games/index", to: "playing_games#index", as: :playing_games_index
     resource :relationships,only:[:create,:destroy]
     get "/relationships/followings",to: "relationships#followings", as: :followings_index
     get "/relationships/followers",to: "relationships#followers", as: :followers_index
    end
    resources :posts,only:[:index,:show,:create,:destroy,:new] do
     patch "/close", to: "posts#close", as: :close
     resources :comments,only:[:create,:destroy]
     resource :favorites,only:[:create,:destroy]
    end
    resources :games,only:[:index,:show]
    get "/search", to: "games#search",as: :search
    resources :chats,only:[:show,:create]
    resources :contacts,only:[:new,:create]
    post "/contacts/confirm",to: "contacts#confirm", as: :confirm
    post "/contacts/back",to: "contacts#back", as: :back
    get "/done",to: "contacts#done", as: :done
    resources :notifications,only:[:index], as: :notifications
    resources :announcements,only:[:index,:show]
  end
# 管理者側ルーティング
  namespace :admin do
   resources :games
   resources :announcements,only:[:new,:create,:edit,:update,:destroy]
   resources :members,only:[:index] do
     patch "/close", to: "members#close"
   end
  end

end

app/models/game.rb
class Game < ApplicationRecord

   validates :name, presence: true
   validates :introduction,presence: true, length: {maximum:150}

  has_many :posts, dependent: :destroy
  has_many :playing_games, dependent: :destroy
  has_many :members, through: :playing_games

  attachment :image
  
  # 部分一致で検索
  def self.search(search)
    if search
      where("name LIKE ?","%#{search}%")
    else
      all
    end
  end

end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController

  before_action :authenticate_admin!

  def index
    @games = Game.all
    if params[:search]
      @games = Game.search(params[:search])
      @famous_games = Game.find(PlayingGame.group(:game_id).order("count(game_id) desc").limit(5).pluck(:game_id))
    else
    #ゲーム人気ランキング
      @famous_games = Game.find(PlayingGame.group(:game_id).order("count(game_id) desc").limit(5).pluck(:game_id))
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    game = Game.new(game_params)
    if game.save
      redirect_to admin_games_path
    else
      @game = game
      render "new"
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    game = Game.find(params[:id])
    game.update(game_params)
    redirect_to admin_games_path
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to admin_games_path
  end

  private

  def game_params
    params.require(:game).permit(:name,:introduction,:image)
  end

end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/views/admin/games/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h3 class="text-center my-5">ゲーム編集ページです</h3>
        <%= form_with model:[:admin,@game], local: true do |f|%>
        <div class="field form-group">
          <%= f.label :image ,"画像を設定："%>
          <%= f.attachment_field :image%>
        </div>
        <div class="field form-group">
          <%= f.label :name ,"ゲーム名"%>
          <%= f.text_field :name ,class:"form-control"%>
        </div>
        <div class="field form-group">
          <%= f.label :introduction ,"説明文"%>
          <%= f.text_area:introduction ,class:"form-control", size:"45x7"%>
        </div>
        <div class="field form-group text-right">
          <%= f.submit "変更を保存する" ,class:"btn btn-success"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/games/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="d-flex justify-content-center my-5">

        <h3 class="mr-5">ゲーム一覧</h3>
        <%= form_with url: admin_games_path,method: :get, local: true do |f| %>
          <%= f.text_field :search, value: params[:search] %>
          <%= f.submit "検索", name: nil %>
        <% end %>
      </div>
      <table class="table w-100 text-left mx-auto">
        <thead class="thead-light d-block" style="width:540px;">
          <tr class="thead-light">
            <th style="width:450px;">ゲーム名</th>
            <th class="text-right" style="width:90px;">編集</th>
          </tr>
        </thead>
        <tbody class="overflow-auto d-block" style="height:400px; width:540px;">
        <% @games.each do |game|%>
        <tr>
          <td class="pt-3" style="width:450px;">
            <%= link_to game_path(game),class:"text-decoration-none" do %>
             <span class="text-decoration-none text-dark">
               <%= attachment_image_tag game, :image, format: "jpg", fallback: "game_icon.jpg",size: "30x30"%>　<%= game.name %>
             </span>
            <% end %>
          </td>
          <td class="text-right" style="width:90px;">
            <%= link_to "編集", edit_admin_game_path(game), class:"btn btn-success"%>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6 mt-5">
      <table class="table mx-auto w-75">
        <tr class="thead-light">
          <th>人気ゲームランキング</th>
        </tr>
        <% @famous_games.each.with_index(1) do |rank, i|%>
          <tr>
            <td><%= i %>位　<%= link_to rank.name, game_path(rank),class:"text-decoration-none"%>(<%= rank.members.count%>人)</td>
          </tr>
        <% end %>
      </table>
      <div class="text-center mt-5">
        <%= link_to "ゲームを追加",new_admin_game_path, class:"btn btn-success"%>
      </div>
    </div>
  </div>
</div>

app/views/admin/games/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h3 class="my-5">新規ゲーム登録ページです</h3>
      <%= form_with model: [:admin,@game], local: true do |f|%>
      <%= render "public/shared/error_messages", resource: @game %>
      <div class="field form-group">
        <%= f.label :image ,"画像を設定："%>
        <%= f.attachment_field :image %>
      </div>
      <div class="field form-group">
        <%= f.label :name ,"ゲーム名"%>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :introduction ,"説明文"%>
        <%= f.text_area :introduction, class:"form-control", size:"45x7" %>
      </div>
      <div class="field form-group text-right">
        <%= f.submit "ゲームを追加する", class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>