config/routes.rb
Rails.application.routes.draw do
 # 管理者側deviseルーティング
  devise_for :admin, skip: :all
   devise_scope :admin do
     get "/admin/sign_in", to: "admin/sessions#new", as: :new_admin_session
     post "/admin/sign_in", to: "admin/sessions#create", as: :admin_session
     delete "/admin/sign_out", to: "admin/sessions#destroy", as: :destroy_admin_session
   end
# メンバー側deviseルーティング
  devise_for :members, skip: :all
   devise_scope :member do
     get "/members/sign_up", to: "public/registrations#new", as: :new_member_registration
     post "/members", to: "public/registrations#create", as: :member_registration
     get "/members/sign_in", to: "public/sessions#new", as: :new_member_session
     post "/members/sign_in", to: "public/sessions#create", as: :member_session
     delete "/members/sign_out", to: "public/sessions#destroy", as: :destroy_member_session
     post '/members/guest_sign_in', to: 'public/sessions#guest_sign_in'
   end
# メンバー側ルーティング
  scope module: :public do
    root :to => "homes#top"
    get "/about" => "homes#about"
    resources :members,only:[:show,:edit,:update] do
     resource :playing_games,only:[:create,:destroy]
     get "/playing_games/index", to: "playing_games#index", as: :playing_games_index
     resource :relationships,only:[:create,:destroy]
     get "/relationships/followings",to: "relationships#followings", as: :followings_index
     get "/relationships/followers",to: "relationships#followers", as: :followers_index
    end
    resources :posts,only:[:index,:show,:create,:destroy,:new] do
     patch "/close", to: "posts#close", as: :close
     resources :comments,only:[:create,:destroy]
     resource :favorites,only:[:create,:destroy]
    end
    resources :games,only:[:index,:show]
    get "/search", to: "games#search",as: :search
    resources :chats,only:[:show,:create]
    resources :contacts,only:[:new,:create]
    post "/contacts/confirm",to: "contacts#confirm", as: :confirm
    post "/contacts/back",to: "contacts#back", as: :back
    get "/done",to: "contacts#done", as: :done
    resources :notifications,only:[:index], as: :notifications
    resources :announcements,only:[:index,:show]
  end
# 管理者側ルーティング
  namespace :admin do
   resources :games
   resources :announcements,only:[:new,:create,:edit,:update,:destroy]
   resources :members,only:[:index] do
     patch "/close", to: "members#close"
   end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameParty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top" style="background-color: #e3f2fd;">
      <div class="container">
        <nav class="navbar navbar-light">
          <%= link_to "GameParty!!", root_path, class:"navbar-brand"%>
          <ul class="nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item mr-2">
                <%= link_to "ゲーム一覧", admin_games_path,class:"nav-link text-dark btn btn-light"%>
              </li>
              <li class="nav-item mr-2">
                <%= link_to "メンバー一覧", admin_members_path,class:"nav-link text-dark btn btn-light"%>
              </li>
              <li class="nav-item mr-2">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:"nav-link text-dark btn btn-light",data: {confirm:"ログアウトしますか？",cancel:"やめる",commit:"ログアウト"},title:"確認"%>
              </li>
              <li class="nav-item mr-2">
                <%= link_to "お知らせ作成", new_admin_announcement_path,class:"nav-link text-dark btn btn-light"%>
              </li>
            <% elsif member_signed_in? %>
              <li class="nav-item mr-2" data-toggle="tooltip" data-placement="bottom" title="お問い合わせ">
                <%= link_to new_contact_path,class:"nav-link text-dark btn btn-light" do %>
                <i class="fas fa-envelope"></i>
                <% end %>
              </li>
              <li class="nav-item mr-2 header_tooltip" data-toggle="tooltip" data-placement="bottom" title="新規投稿">
                <%= link_to new_post_path,class:"nav-link text-dark btn btn-light" do%>
                <i class="fas fa-plus"></i>
                <% end %>
              </li>
              <li class="nav-item mr-2 header_tooltip" data-toggle="tooltip" data-placement="bottom" title="フォロー投稿">
                <%= link_to posts_path,class:"nav-link text-dark btn btn-light" do %>
                <i class="fas fa-users"></i>
                <% end %>
              </li>
              <li class="nav-item mr-2 header_tooltip" data-toggle="tooltip" data-placement="bottom" title="ゲーム一覧">
                <%= link_to games_path,class:"nav-link text-dark btn btn-light" do %>
                <i class="fas fa-gamepad"></i>
                <% end %>
              </li>
              <% if unchecked_notifications.any? %>
                <i class="fa fa-circle" style="color: red;"></i>
              <% end %>
              <li class="nav-item mr-2 header_tooltip"  data-toggle="tooltip" data-placement="bottom" title="通知">
                <%= link_to notifications_path,class:"nav-link text-dark btn btn-light" do%>
                <i class="fas fa-bell"></i>
                <% end %>
              </li>
              <li class="nav-item mr-2 header_tooltip" data-toggle="tooltip" data-placement="bottom" title="マイページ">
                <%= link_to member_path(current_member),class:"nav-link btn btn-light",style:"height: 42px;" do%>
                <%= attachment_image_tag current_member, :image, format: "jpg", fallback: "member_img.jpg",size: "30x30",class:"rounded-circle border"%>
                <% end %>
              </li>
              <li class="nav-item mr-2 header_tooltip" data-toggle="tooltip" data-placement="bottom" title="ログアウト">
                <%= link_to destroy_member_session_path, method: :delete,class:"nav-link text-dark btn btn-light",data: {confirm:"ログアウトしますか？",cancel:"やめる",commit:"ログアウト"},title:"確認" do %>
                <i class="fas fa-sign-out-alt"></i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item mr-2">
                <%= link_to "アバウト",about_path,class:"nav-link text-dark btn btn-light"%>
              </li>
              <li class="nav-item mr-2">
                <%= link_to "新規登録", new_member_registration_path,class:"nav-link text-dark btn btn-light" %>
              </li>
              <li class="nav-item mr-2">
                <%= link_to "ログイン", new_member_session_path,class:"nav-link text-dark btn btn-light" %>
              </li>
              <li class="nav-item mr-2">
              <%= link_to "お問い合わせ",new_contact_path,class:"nav-link text-dark btn btn-light"%>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer class="mt-3">
      <div class="container">
        <div class="row justify-content-center">
          <p>Game Party!!</p>
        </div>
      </div>
    </footer>

  </body>
</html>